from badword_corpus import *
from commonphrases_corpus import *
from dale_corpus import *
from dictionary_corpus import *
from domain_corpus import *
from doubleword_corpus import *
from knownphrases_corpus import *
from misspelling_corpus import *
from namecalling_corpus import *
from names_corpus import *
from netlingo_corpus import *
from netlingo_long_corpus import *
from noise_corpus import *
from slang_corpus import *
from transpose_corpus import *
from twittercommonwords_corpus import *
from twlingo_corpus import *
