""" bad word list
Copyright 2009 Carlos Justiniano. All Rights Reserved.
"""

bad_words = [
    "airhead",
    "anus",
    "ass",
    "ass lick",
    "asshole",
    "asskisser",
    "asswipe",
    "bastard",
    "belly whacker",
    "bitch",
    "bitches",
    "bitty",
    "blow job",
    "blowjob",
    "bonehead",
    "boner",
    "boob",
    "booger",
    "bufu",
    "bull shit",
    "bullshit",
    "bung hole",
    "butch",
    "butt",
    "butt breath",
    "butt fucker",
    "butt hair",
    "buttface",
    "buttfuck",
    "buttfucker",
    "butthead",
    "buthead",
    "butthole",
    "butthole sweat",
    "buttpicker",
    "call girl",
    "chink",
    "clit",
    "cobia",
    "cock",
    "cocksucker",
    "cooter",
    "crap",
    "crusty crotch",
    "cum",
    "cumn",
    "cunnilingus",
    "cunt",
    "cunt lick",
    "cunt lip",
    "cuntbreath",
    "cuntdog",
    "cuntsucker",
    "dag gummit",
    "damn",
    "damn it",
    "damned",
    "damnit",
    "dick brain",
    "dick breath",
    "dick cheese",
    "dick face",
    "dick head",
    "dick sucker",
    "dick wrinkle",
    "dickbreath",
    "dickface",
    "dickhead",
    "dickless",
    "dicksmack",
    "dicksucker",
    "dike",
    "dildo",
    "dilldoe",
    "dilldos",
    "dio",
    "dipshit",
    "doggie style",
    "dong",
    "douche bag",
    "douche juice",
    "dum",
    "dumb ass",
    "dumbass",
    "dumbbell",
    "dyke",
    "fag",
    "fagget",
    "faggit",
    "faggot",
    "faggot ass",
    "fagit",
    "fareskin",
    "fatass",
    "fatso",
    "friggin",
    "from hell",
    "fuck",
    "fucker",
    "fucking",
    "fuck ass",
    "fuck face",
    "fuck me",
    "fuck off",
    "fuck up",
    "fuckbutt",
    "fucker",
    "fuckface",
    "fuckhead",
    "fucking",
    "fucking bitch",
    "fucking shit",
    "fuckup",
    "furburger",
    "gazongers",
    "god damn",
    "god damn it",
    "god damn whore",
    "god damned",
    "god damnit",
    "goddam",
    "goddammit",
    "goddamn",
    "gonads",
    "gook",
    "got damn",
    "got damn it",
    "guinne",
    "hard on",
    "ho",
    "hoar",
    "homo",
    "honker",
    "honky",
    "hooker",
    "hooters",
    "horny",
    "hussy",
    "jack off",
    "jackass",
    "jacking off",
    "jackoff",
    "jap",
    "jeez",
    "jerk",
    "jew",
    "jizz",
    "keaster",
    "kike",
    "knob",
    "kraut",
    "lesbian",
    "lesbo",
    "lessy",
    "lick my cunt",
    "lier",
    "masturbate",
    "merde",
    "mierda",
    "motherfucker",
    "muff",
    "mutherfucker",
    "necrophilia",
    "nigga",
    "nigger",
    "niqqa",
    "niggas",
    "nigger lover",
    "nigger shit",
    "pecker",
    "peckerhead",
    "penis",
    "penis breath",
    "penis head",
    "penis wrinkle",
    "pimp",
    "piss",
    "piss ant",
    "piss off",
    "pissed",
    "pissed off",
    "polack",
    "poo poo",
    "poontang",
    "prick",
    "prostitute",
    "punk",
    "puntang",
    "pussy",
    "pussy lip",
    "pussy lips",
    "pussy whip",
    "pussydick",
    "pussylips",
    "queer",
    "rat bastard",
    "rat bastards",
    "ream",
    "retard",
    "rump ranger",
    "schlong",
    "schmeka",
    "scrog",
    "sheister",
    "shit",
    "shitting",
    "shitty",
    "shit ass",
    "shit face",
    "shit for brains",
    "shit head",
    "shitass",
    "shitface",
    "shithead",
    "shithloe",
    "shithole",
    "shiting",
    "shlong",
    "shmegma",
    "shoot",
    "shooting a wade",
    "shut up",
    "slackass",
    "slag",
    "sleeze",
    "slit",
    "slut",
    "slutty bitch",
    "smagna",
    "snatch",
    "son of a bitch",
    "son of a whore",
    "spic",
    "strap on",
    "stupid",
    "suck",
    "suck my dick",
    "sucker",
    "suckes",
    "ticked off",
    "tit",
    "tits",
    "titty",
    "titty sucker",
    "toe jam",
    "tramp",
    "twat",
    "up the butt",
    "vertical taco",
    "vitrator",
    "wanker",
    "weat back",
    "wetback",
    "whore",
    "wop",
    "yellow rat bastard",
    "your mama",
    "your mother",
    "*"
]

bad_words.sort()
