""" bad word list
Copyright (c) 2013, Carlos Justiniano
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

bad_words = [
    "airhead",
    "anus",
    "ass",
    "ass lick",
    "asshole",
    "asskisser",
    "asswipe",
    "bastard",
    "belly whacker",
    "bitch",
    "bitches",
    "bitty",
    "blow job",
    "blowjob",
    "bonehead",
    "boner",
    "boob",
    "booger",
    "bufu",
    "bull shit",
    "bullshit",
    "bung hole",
    "butch",
    "butt",
    "butt breath",
    "butt fucker",
    "butt hair",
    "buttface",
    "buttfuck",
    "buttfucker",
    "butthead",
    "buthead",
    "butthole",
    "butthole sweat",
    "buttpicker",
    "call girl",
    "chink",
    "clit",
    "cobia",
    "cock",
    "cocksucker",
    "cooter",
    "crap",
    "crusty crotch",
    "cum",
    "cumn",
    "cunnilingus",
    "cunt",
    "cunt lick",
    "cunt lip",
    "cuntbreath",
    "cuntdog",
    "cuntsucker",
    "dag gummit",
    "damn",
    "damn it",
    "damned",
    "damnit",
    "dick brain",
    "dick breath",
    "dick cheese",
    "dick face",
    "dick head",
    "dick sucker",
    "dick wrinkle",
    "dickbreath",
    "dickface",
    "dickhead",
    "dickless",
    "dicksmack",
    "dicksucker",
    "dike",
    "dildo",
    "dilldoe",
    "dilldos",
    "dio",
    "dipshit",
    "doggie style",
    "dong",
    "douche bag",
    "douche juice",
    "dum",
    "dumb ass",
    "dumbass",
    "dumbbell",
    "dyke",
    "fag",
    "fagget",
    "faggit",
    "faggot",
    "faggot ass",
    "fagit",
    "fareskin",
    "fatass",
    "fatso",
    "friggin",
    "from hell",
    "fuck",
    "fucker",
    "fucking",
    "fuck ass",
    "fuck face",
    "fuck me",
    "fuck off",
    "fuck up",
    "fuckbutt",
    "fucker",
    "fuckface",
    "fuckhead",
    "fucking",
    "fucking bitch",
    "fucking shit",
    "fuckup",
    "furburger",
    "gazongers",
    "god damn",
    "god damn it",
    "god damn whore",
    "god damned",
    "god damnit",
    "goddam",
    "goddammit",
    "goddamn",
    "gonads",
    "gook",
    "got damn",
    "got damn it",
    "guinne",
    "hard on",
    "ho",
    "hoar",
    "homo",
    "honker",
    "honky",
    "hooker",
    "hooters",
    "horny",
    "hussy",
    "jack off",
    "jackass",
    "jacking off",
    "jackoff",
    "jap",
    "jeez",
    "jerk",
    "jew",
    "jizz",
    "keaster",
    "kike",
    "knob",
    "kraut",
    "lesbian",
    "lesbo",
    "lessy",
    "lick my cunt",
    "lier",
    "masturbate",
    "merde",
    "mierda",
    "motherfucker",
    "muff",
    "mutherfucker",
    "necrophilia",
    "nigga",
    "nigger",
    "niqqa",
    "niggas",
    "nigger lover",
    "nigger shit",
    "pecker",
    "peckerhead",
    "penis",
    "penis breath",
    "penis head",
    "penis wrinkle",
    "pimp",
    "piss",
    "piss ant",
    "piss off",
    "pissed",
    "pissed off",
    "polack",
    "poo poo",
    "poontang",
    "prick",
    "prostitute",
    "punk",
    "puntang",
    "pussy",
    "pussy lip",
    "pussy lips",
    "pussy whip",
    "pussydick",
    "pussylips",
    "queer",
    "rat bastard",
    "rat bastards",
    "ream",
    "retard",
    "rump ranger",
    "schlong",
    "schmeka",
    "scrog",
    "sheister",
    "shit",
    "shitting",
    "shitty",
    "shit ass",
    "shit face",
    "shit for brains",
    "shit head",
    "shitass",
    "shitface",
    "shithead",
    "shithloe",
    "shithole",
    "shiting",
    "shlong",
    "shmegma",
    "shoot",
    "shooting a wade",
    "shut up",
    "slackass",
    "slag",
    "sleeze",
    "slit",
    "slut",
    "slutty bitch",
    "smagna",
    "snatch",
    "son of a bitch",
    "son of a whore",
    "spic",
    "strap on",
    "stupid",
    "suck",
    "suck my dick",
    "sucker",
    "suckes",
    "ticked off",
    "tit",
    "tits",
    "titty",
    "titty sucker",
    "toe jam",
    "tramp",
    "twat",
    "up the butt",
    "vertical taco",
    "vitrator",
    "wanker",
    "weat back",
    "wetback",
    "whore",
    "wop",
    "yellow rat bastard",
    "your mama",
    "your mother",
    "*"
]

bad_words.sort()
