""" common phrases list
Copyright 2009 Carlos Justiniano. All Rights Reserved.
"""

common_phrases = [
    "bad day",
    "bad news",
    "banner ads",
    "beautiful day",
    "best selling",
    "best thing",
    "best way",
    "blog post",
    "brand new",
    "certain things",
    "cool things",
    "daily round",
    "days later",
    "direct message",
    "domain name",
    "domain names",
    "e g",
    "few days",
    "few hours",
    "few minutes",
    "few years",
    "fine bloggers",
    "first time",
    "follow friday",
    "follow list",
    "followfriday",
    "followfridays",
    "followlist",
    "friday morning",
    "friday night",
    "front row",
    "fun stuff",
    "good afternoon",
    "good bye",
    "good evening",
    "good luck",
    "good morning",
    "good news",
    "good night",
    "good points",
    "good stuff",
    "good thing",
    "good ways",
    "good year",
    "good years",
    "great day",
    "great idea",
    "great job",
    "great people",
    "great thing",
    "great time",
    "great times",
    "great week",
    "great weekend",
    "great work",
    "guest post",
    "ha ha ha",
    "ha ha",
    "happy birthday",
    "home page",
    "info",
    "interesting read",
    "last day",
    "last minute",
    "last minutes",
    "last month",
    "last night",
    "last time",
    "last tweet",
    "last week",
    "last year",
    "late night",
    "later today",
    "latest version",
    "less time",
    "live chat",
    "long time",
    "many people",
    "many ways",
    "monday morning",
    "monday night",
    "more day",
    "more info",
    "more people",
    "more time",
    "more times",
    "most software",
    "multi",
    "new blog post",
    "new blog",
    "new issue",
    "new post",
    "new posts",
    "new project",
    "new study",
    "new twitter",
    "new way",
    "new ways",
    "new world",
    "new year",
    "next month",
    "next time",
    "next week",
    "next year",
    "nice work",
    "official site",
    "oh boy",
    "oh no",
    "oh yes",
    "one day",
    "one else",
    "only one",
    "please let",
    "real world",
    "retweet",
    "rt",
    "safe travels",
    "same goes",
    "same thing",
    "same time",
    "same way",
    "saturday morning",
    "saturday night",
    "search results",
    "some thing",
    "special thanks",
    "sunday morning",
    "sunday night",
    "tech",
    "thursday morning",
    "thursday night",
    "tomorrow morning",
    "top 10",
    "top selling",
    "tuesday morning",
    "tuesday night",
    "twitter account",
    "twitter name",
    "twitter users",
    "web application",
    "web applications",
    "web browser",
    "web site",
    "wednesday morning",
    "wednesday night",
    "whole new",
    "wonderful thing",
    "years old",
    "yesterday",
    "*"
]

common_phrases.sort()

