""" common phrases list
Copyright (c) 2013, Carlos Justiniano
All rights reserved.

Redistribution and use in source and binary forms, with or without
modification, are permitted provided that the following conditions are met:
    * Redistributions of source code must retain the above copyright
      notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright
      notice, this list of conditions and the following disclaimer in the
      documentation and/or other materials provided with the distribution.
    * Neither the name of the <organization> nor the
      names of its contributors may be used to endorse or promote products
      derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND
ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED
WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
DISCLAIMED. IN NO EVENT SHALL <COPYRIGHT HOLDER> BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES
(INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND
ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT
(INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
"""

common_phrases = [
    "bad day",
    "bad news",
    "banner ads",
    "beautiful day",
    "best selling",
    "best thing",
    "best way",
    "blog post",
    "brand new",
    "certain things",
    "cool things",
    "daily round",
    "days later",
    "direct message",
    "domain name",
    "domain names",
    "e g",
    "few days",
    "few hours",
    "few minutes",
    "few years",
    "fine bloggers",
    "first time",
    "follow friday",
    "follow list",
    "followfriday",
    "followfridays",
    "followlist",
    "friday morning",
    "friday night",
    "front row",
    "fun stuff",
    "good afternoon",
    "good bye",
    "good evening",
    "good luck",
    "good morning",
    "good news",
    "good night",
    "good points",
    "good stuff",
    "good thing",
    "good ways",
    "good year",
    "good years",
    "great day",
    "great idea",
    "great job",
    "great people",
    "great thing",
    "great time",
    "great times",
    "great week",
    "great weekend",
    "great work",
    "guest post",
    "ha ha ha",
    "ha ha",
    "happy birthday",
    "home page",
    "info",
    "interesting read",
    "last day",
    "last minute",
    "last minutes",
    "last month",
    "last night",
    "last time",
    "last tweet",
    "last week",
    "last year",
    "late night",
    "later today",
    "latest version",
    "less time",
    "live chat",
    "long time",
    "many people",
    "many ways",
    "monday morning",
    "monday night",
    "more day",
    "more info",
    "more people",
    "more time",
    "more times",
    "most software",
    "multi",
    "new blog post",
    "new blog",
    "new issue",
    "new post",
    "new posts",
    "new project",
    "new study",
    "new twitter",
    "new way",
    "new ways",
    "new world",
    "new year",
    "next month",
    "next time",
    "next week",
    "next year",
    "nice work",
    "official site",
    "oh boy",
    "oh no",
    "oh yes",
    "one day",
    "one else",
    "only one",
    "please let",
    "real world",
    "retweet",
    "rt",
    "safe travels",
    "same goes",
    "same thing",
    "same time",
    "same way",
    "saturday morning",
    "saturday night",
    "search results",
    "some thing",
    "special thanks",
    "sunday morning",
    "sunday night",
    "tech",
    "thursday morning",
    "thursday night",
    "tomorrow morning",
    "top 10",
    "top selling",
    "tuesday morning",
    "tuesday night",
    "twitter account",
    "twitter name",
    "twitter users",
    "web application",
    "web applications",
    "web browser",
    "web site",
    "wednesday morning",
    "wednesday night",
    "whole new",
    "wonderful thing",
    "years old",
    "yesterday",
    "*"
]

common_phrases.sort()

