""" known phrases
Copyright 2009 Carlos Justiniano. All Rights Reserved.
"""

known_phrases = [
    "aaron carter",
    "abigail breslin",
    "adam brody",
    "adolf hitler",
    "adrienne king",
    "albert einstein",
    "alexander the great",
    "alexandre von furstenberg",
    "ali macgraw",
    "alicia keys",
    "alicia witt",
    "alyson michalka",
    "amanda bynes",
    "amanda seyfried",
    "american samoa",
    "amy smart",
    "andrew garfield",
    "anna faris",
    "anne lennox",
    "annie parisse",
    "anson mount",
    "anton yelchin",
    "ashlee simpson",
    "ashley tisdale",
    "ashton kutcher",
    "aubrey graham",
    "balthazar getty",
    "barack obama",
    "ben foster",
    "ben lyons",
    "benicio del toro",
    "benjamin mckenzie",
    "bertrand russell",
    "beverly d'angelo",
    "bill gates",
    "blake foster",
    "blake lively",
    "bob hoskins",
    "bouvet island",
    "bow wow",
    "brad renfro",
    "brendan fraser",
    "brian thomas littrell",
    "briana evigan",
    "brie larson",
    "britney spears",
    "brittany murphy",
    "brooke shields",
    "bruce willis",
    "bryan greenberg",
    "bryce dallas howard",
    "burkina faso",
    "burt reynolds",
    "caitlin wachs",
    "cameron diaz",
    "campbell scott",
    "cape verde",
    "carmen electra",
    "cary elwes",
    "cayman islands",
    "central african republic",
    "chace crawford",
    "chad michael murray",
    "channing tatum",
    "charles darwin",
    "chevy chase",
    "chris brown",
    "chris klein",
    "chris pine",
    "chris sarandon",
    "chris tucker",
    "christian bale",
    "christina ricci",
    "christmas island",
    "christopher atkins",
    "christopher mcdonald",
    "clay aiken",
    "clive owen",
    "cloris leachman",
    "cocos islands",
    "cody linley",
    "cole and dylan sprouse",
    "colin hanks",
    "columbus day",
    "cook islands",
    "corbin bleu",
    "costa rica",
    "czech republic",
    "dakota fanning",
    "daniel radcliffe",
    "david boreanaz",
    "david strathairn",
    "dawn cody",
    "dee wallace-stone",
    "demi moore",
    "denise richards",
    "dennis quaid",
    "denzel washington",
    "diana spencer",
    "diane keaton",
    "diane lane",
    "dick cheney",
    "dirk benedict",
    "dominican republic",
    "donald trump",
    "douglas smith",
    "drake bell",
    "drea de matteo",
    "drew barrymore",
    "earle page",
    "east timor",
    "edward jenner",
    "el salvador",
    "elijah wood",
    "elisabeth shue",
    "eliza dushku",
    "elizur holyoke",
    "emile hirsch",
    "emma roberts",
    "emma stone",
    "emma watson",
    "equatorial guinea",
    "erik von detten",
    "erika christensen",
    "ethan hawke",
    "eva longoria",
    "eva mylott",
    "evan rachel wood",
    "ewan mcgregor",
    "falkland islands",
    "faroe islands",
    "fiji islands",
    "forest whitaker",
    "forrest landis",
    "frankie muniz",
    "franklin pierce",
    "fred thompson",
    "freddie highmore",
    "freddie prinze, jr.",
    "french guiana",
    "french polynesia",
    "gabriel macht",
    "gene hackman",
    "george bush",
    "george clooney",
    "george eads",
    "george herbert walker bush",
    "george keppel",
    "george washington",
    "gregory smith",
    "greta scacchi",
    "guy ritchie",
    "gwyneth paltrow",
    "harold holt",
    "harrison ford",
    "harry crosby",
    "harry s. truman",
    "harvey keitel",
    "hayden christensen",
    "hayden panettiere",
    "haylie duff",
    "heath ledger",
    "helena bonham carter",
    "henry keppel",
    "henry thomas",
    "hilary duff",
    "hilary swank",
    "hong kong",
    "hope davis",
    "hugh grant",
    "humphrey bogart",
    "ice cube",
    "jack black",
    "jackie chan",
    "jackson rathone (1984)",
    "jacob kogan",
    "jaime king",
    "jake epstein",
    "jake gyllenhaal",
    "james dixon robinson iii",
    "james franco",
    "james lipton",
    "jamie lynn spears",
    "jane fonda",
    "jared padalecki",
    "jason behr",
    "jason patric",
    "jason robards jr.",
    "jason segel",
    "javier bardem",
    "jay brannan",
    "jennifer lopez",
    "jennifer love hewitt",
    "jensen ackles",
    "jesse eisenberg",
    "jesse mccartney",
    "jessica alba",
    "jessica simpson",
    "jimmy fallon",
    "joan allen",
    "jodie foster",
    "joe flanigan",
    "john adams",
    "john f. kennedy",
    "john forsythe",
    "john howard",
    "john leguizamo",
    "john rhys-davies",
    "john russell",
    "johnny whitaker",
    "jonah hill",
    "jonathan taylor thomas",
    "jordan bridges",
    "jordan ladd",
    "joseph fiennes",
    "joseph gordon-levitt",
    "josh hartnett",
    "josh hutcherson",
    "joshua jackson",
    "jurnee smollett",
    "justin berfield",
    "justin long",
    "justin timberlake",
    "karen black",
    "kat dennings",
    "kate hudson",
    "katharine hepburn",
    "katharine mcphee",
    "katherine heigl",
    "katie holmes",
    "keith coogan",
    "kelly clarkson",
    "keri russell",
    "kevin bacon",
    "kevin costner",
    "kevin federline",
    "kevin rudd",
    "kevin scott richardson",
    "kevin sorbo",
    "khleo thomas",
    "kristanna loken",
    "kristen bell",
    "kyra sedgwick",
    "lake bell",
    "lar park lincoln",
    "lauren bacall",
    "laurence fishburne",
    "leelee sobieski",
    "leonardo dicaprio",
    "lindsay lohan",
    "lindsey buckingham",
    "liv tyler",
    "liza minnelli",
    "logan lerman",
    "loretta devine",
    "los angeles",
    "mackenzie astin",
    "madonna",
    "maggie grace",
    "mandy moore",
    "marge helgenberger",
    "margo harshman",
    "maria bello",
    "mark rendall",
    "marley shelton",
    "marshall islands",
    "mary chapin carpenter",
    "mary steenburgen",
    "mary stuart",
    "matt dillon",
    "matt lanter",
    "matt prokop",
    "matthew broderick",
    "matthew fox",
    "matthew mcconaughey",
    "max thieriot",
    "meagan good",
    "meg ryan",
    "mel gibson",
    "melissa george",
    "meryl streep",
    "michael angarano",
    "michael cera",
    "michael clarke duncan",
    "michael urie",
    "michael vartan",
    "michelle trachtenberg",
    "mickey rourke",
    "milena govich",
    "miley cyrus",
    "morgan freeman",
    "naomi watts",
    "nat wolff",
    "natalie portman",
    "netherlands antilles",
    "neve campbell",
    "new caledonia",
    "new hampshire",
    "new jersey",
    "new mexico",
    "new york",
    "new zealand",
    "nick cannon",
    "nick carter",
    "nick drago",
    "nick jonas",
    "nicole kidman",
    "nicole richie",
    "norfolk island",
    "north carolina",
    "north dakota",
    "north korea",
    "northern mariana islands",
    "oliver cromwell",
    "oz perkins",
    "papua new guinea",
    "paris hilton",
    "patricia clarkson",
    "patrick flueger",
    "paul rudd",
    "penelope cruz",
    "pete wentz",
    "pier gerlofs donia",
    "puerto rico",
    "queen latifah",
    "rachael macfarlane",
    "rachel bilson",
    "rachel mcadams",
    "rachel weisz",
    "rafi gavron",
    "randall batinkoff",
    "raven-symone",
    "ray liotta",
    "rhode island",
    "richard jenkins",
    "richard tol",
    "ricky ullman",
    "river phoenix",
    "rob lowe",
    "robby benson",
    "robert downey",
    "robert hoffman",
    "robert james woolsey",
    "ron perlman",
    "rosario dawson",
    "rupert everett",
    "rupert grint",
    "russian federation",
    "ryan gosling",
    "ryan o'neal",
    "ryan phillippe?",
    "ryan reynolds",
    "saint helena",
    "saint lucia",
    "sam neill",
    "sam waterston",
    "samantha harris",
    "samuel l. jackson",
    "san andreas fault",
    "san andreas",
    "san antonio",
    "san benito",
    "san diego",
    "san fran",
    "san francisco bay",
    "san francisco chronicle",
    "san francisco",
    "san franscico",
    "san jose",
    "san marino",
    "san mateo",
    "sand hill rd",
    "sand hill",
    "sandberg",
    "sands research",
    "santa claus",
    "santa cruz",
    "santa francisco bay",
    "santa francisco",
    "santa lucia",
    "santa monica airport",
    "santa monica pier",
    "santa monica",
    "sara paxton",
    "sarah bolger",
    "sarah jessica parker",
    "sarah michelle gellar",
    "saudi arabia",
    "scarlett johansson",
    "sean bean",
    "sean faris",
    "sean penn",
    "seth macfarlane",
    "seth rogen",
    "shane west",
    "shannon elizabeth",
    "shaukat ali abdul ghafoor",
    "shelley winters",
    "shia labeouf",
    "shirley maclaine?",
    "sid haig",
    "sierra leone",
    "sigourney weaver",
    "sir walter raleigh",
    "skeet ulrich",
    "solomon islands",
    "sonia cubitt",
    "south africa",
    "south carolina",
    "south dakota",
    "south korea",
    "sri lanka",
    "stephanie march",
    "stephen colletti",
    "steve zahn",
    "steven r mcqueen",
    "sylvester stallone",
    "taylor ball",
    "teddy geiger",
    "tel aviv",
    "terrence howard",
    "thomas jane",
    "thora birch",
    "todd lowe",
    "todd oldham",
    "tom cruise",
    "tom ridge",
    "tom welling",
    "toni collette",
    "tony denman",
    "tracy morgan",
    "tyler hilton",
    "uma thurman",
    "united arab emirates",
    "united kingdom",
    "united states",
    "val kilmer",
    "vanessa anne hudgens",
    "virgin islands",
    "walter raleigh",
    "west virginia",
    "western sahara",
    "whoopi goldberg",
    "will ferrell",
    "william fargo",
    "william hovell",
    "william iii of england",
    "william john hamilton",
    "william mapother",
    "william richard hamilton",
    "william sotheby",
    "william windsor",
    "winona ryder",
    "woody allen",
    "zac efron",
    "*"
]

known_phrases.sort()
