""" net lingo dictionary
Copyright 2009 Carlos Justiniano. All Rights Reserved.
"""

net_lingo = {
    "2nite": "tonight",
    "4ever": "forever",
    "4got": "forgot",
    "4give": "forgive",
    "4u": "for you",
    "4me": "for me",
    "a**": "ass",
    "afaik": "as far as i know",
    "btw": "by the way",
    "cmon": "come on",
    "cya": "see you later",
    "fyi": "for your information",
    "ftw": "for the win",
    "gr8": "great",
    "haha": " ",
    "hahaha": " ",
    "imao": "in my arrogant opinion",
    "imho": "in my humble opinion",
    "l33t": "elite",
    "l8r": "later",
    "lol": "laughing out loud",
    "lovin": "loving",
    "omg": "oh my god",
    "pls": "please",
    "plz": "please",
    "ppl": "people",
    "rofl": "rolling on floor laughing",
    "rotfl": "rolling on the floor laughing",
    "sup": "what is up",
    "tbc": "to be continued",
    "tbd": "to be determined",
    "tgif": "thank god it is friday",
    "thx": "thanks",
    "thnx": "thanks",
    "w": "with",
    "w/": "with",
    "wtf": "what the fuck",
    "xoxoxo": "hugs & kisses",
    ":)": "smile",
    ":-)": "smile",
    ":-e": "buck-tooth",
    "<33": "enthusiastic",
    ">-)": "evil grin",
    ":(": "sad or frown smile",
    ":-(": "sad with nose",
    ":-<": "super sad",
    "(((h)))": "hugs",
    ":-x": "kiss on the lips",
    "`:-)": "one eyebrow raised",
    ":^)": "a broken nose",
    ":-&": "tongue tied",
    "e-:-)": "a ham radio operator",
    ":-#": "with braces",
    ":'-)": "happy crying",
    ";)": "winking smile",
    ";-)": "winking smile with nose",
    ":-D": "laughing",
    ":D": "laughing",
    "o:-)": "i am a boy angel",
    "o*-)": "i am a girl angel",
    "(:-d": "gossip, blabbermouth",
    "@>--;--": "rose",
    "=^.^=": "cat",
    "o.o": "confused",
    "c=:-)": "a chef",
    ":-!": "foot in mouth",
    ":-d": "laughter",
    ":*)": "drunk smile",
    ":@": "exclamation what",
    ":-@": "scream",
    ":-0": "yell",
    "%-(": "confused",
    ":-----)": "long nose (liar!)",
    ":-.)": "madonna",
    ":-($)": "put your money where your mouth is",
    "(:i": "an egghead",
    "|-o": "yawning",
    "$#!+": "shit",
    "$46": "money for sex",
    "$h!t": "shit",
    "$xy": "sexy",
    "/.": "slashdot",
    "*4u": "kiss for you",
    "*eg*": "evil grin",
    "10tacle": "tentacle",
    "10x": "thanks",
    "12b": "wannabe",
    "1337": "elite",
    "133t": "elite",
    "13itch": "bitch",
    "1ab": "wannabe",
    "1sec": "one second",
    "2day": "today",
    "2moro": "tomorrow",
    "2morow": "tomorrow",
    "2morro": "tomorrow",
    "2morrow": "tommorrow",
    "<3": "love",
    "?u@": "where are you",
    "?up": "what is up",
    "?^": "what is up",
    "@": "at",
    "@$$": "ass",
    "@$$ #013": "ass hole",
    "@$$hole": "asshole",
    "@h": "asshole",
    "^5": "high five",
    ">3": "love",
    "?4u": "question for you",
    "a$$": "ass",
    "alot": "a lot",
    "avie": "avatar",
    "b/w": "between",
    "b1tch": "bitch",
    "b2b": "business to business",
    "betch": "bitch",
    "betcha": "bet you",
    "brb": "be right back",
    "celly": "cell phone",
    "comin'": "coming",
    "cu": "goodbye",
    "cuz": "because",
    "dat": "that",
    "dats": "that is",
    "dunno": "i do not know",
    "duno": "do not know",
    "el!t": "elite",
    "ello": "hello",
    "elo": "hello",
    "evry": "every",
    "ex-bf": "ex-boy friend",
    "ex-gf": "ex-girl friend",
    "exp": "experience",
    "f u": "fuck you",
    "frag": "kill",
    "fragged": "killed",
    "fu": "fuck you",
    "gby": "good bye",
    "gcad": "get cancer and die",
    "gcf": "google click fraud",
    "gd": "good",
    "h4kz0r5": "hackers",
    "h4x": "hacks",
    "h4x0r": "hacker",
    "h4xor": "hacker",
    "h4xr": "hacker",
    "h4xrz": "hackers",
    "h4xx0rz": "hacker",
    "h4xxor": "hacker",
    "h80r": "hater",
    "h83r": "hater",
    "h8er": "hater",
    "h8r": "hater",
    "h8red": "hatred",
    "h8s": "hates",
    "h8t": "hate",
    "h8t0r": "hater",
    "h8t3r": "hater",
    "h8te": "hate",
    "h8tr": "hater",
    "hax0r": "hacker",
    "hax0red": "hacked",
    "hax0rz": "hackers",
    "haxer": "hacker",
    "haxor": "hacker",
    "haxoring": "hacking",
    "haxors": "hackers",
    "haxorz": "hackers",
    "haxxor": "hacker",
    "haxz0r": "hacker",
    "haxzor": "hacker",
    "heh": " ",
    "i<3 u": "i love you",
    "i<3u": "i love you",
    "kuwl": "cool",
    "kwik": "quick",
    "luv": "love",
    "luver": "lover",
    "muzik": "music",
    "orly": "oh really"
}
