slangLingo = {
"2c":"to see",
"aiiqht":"alright",
"aint":"am not",
"altho":"although",
"aw":" ",
"azz":"ass",
"b":"be",
"blah":" ",
"bro":"brother",
"bros":"brothers",
"c'mon":"come on",
"cmon":"come on",
"comin":"coming",
"coulda":"could have",
"cuz":"because",
"da":"the",
"dah":"the",
"dat":"that",
"dats":"that is",
"diss":"this",
"doh":" ",
"duh":" ",
"eh":" ",
"gawd":"oh my god",
"gonna":"going to",
"gotta":"have to",
"happenin":"happening",
"hatin":"hating",
"hmm":" ",
"huh":"what",
"ignant":"ignorant",
"im":"i am",
"ima":"i am",
"imma":"I am going to",
"jus":"just",
"kinda":"kind of",
"kno":"know",
"lemme":"let me",
"lil":"little",
"lookie":"look at",
"lov":"love",
"hurray": " ",
"motha":"mother",
"n":"and",
"neitha":"either",
"neva":"never",
"nite":"night",
"nobody":"no one",
"o":"oh",
"outta":"out of",
"r":"are",
"ridic":"ridiculous",
"shoulda":"should have",
"shxt":"shit",
"sistah":"sister",
"takin":"taking",
"tho":"though",
"u":"you",
"uh":" ",
"um":" ",
"umm":" ",
"ur":"you are",
"waitin":"waiting",
"wat":"what",
"wats":"what is",
"wen":"when",
"wenever":"when ever",
"whateva":"what ever",
"whoa":"wow",
"woot":" ",
"wit":"with",
"witcha":"with you",
"woulda":"would have",
"wun":"will not",
"y'all":"you all",
"ya":"your",
"yall":"you all",
"yah":"yes",
"yay":" ",
"yep":"yes",
"yo":"your",
"yup":"yes",
"*":"*"
}

