""" transposition list
Copyright 2009 Carlos Justiniano. All Rights Reserved.
"""

transpose_map = {
    "2nd": "second",
    "2nite": "tonight",
    "2night": "tonight",
    "4real": "for real",
    "aher'dat": "i hear that",
    "ain't": "is not",
    "aren't": "are not",
    "any1": "any one",
    "b'berries": "blue berries",
    "b0ut": "about",
    "c'mon": "come on",
    "can't": "can not",
    "couldn't": "could not",
    "diff": "difference",
    "didn't": "did not",
    "doesn't": "does not",
    "don't": "do not",
    "gov't": "government",
    "hasn't": "has not",
    "haven't": "have not",
    "he'd": "he would",
    "he'll": "he will",
    "he's": "he is",
    "in2": "into",
    "i'd": "i would",
    "i'll": "i will",
    "i'm": "i am",
    "ive": "i have",
    "i've": "i have",
    "incl": "include",
    "intro": "introduction",
    "isn't": "is not",
    "it's": "it is",
    "let's": "let us",
    "lets": "let us",
    "oft": "often",
    "orly": "oh really",
    "ppl": "people",
    "re": "reference",
    "ref": "reference",
    "she'd": "she would",
    "she'll": "she will",
    "she's": "she is",
    "shouldn't": "should not",
    "sync": "synchronize",
    "sh*t": "shit",
    "that's": "that is",
    "thats": "that is",
    "that'd": "that would",
    "they'd": "they would",
    "they'll": "they will",
    "they're": "they are",
    "w/": "with",
    "wait'll": "wait until",
    "wasn't": "was not",
    "we'd": "we would",
    "we'll": "we will",
    "we're": "we are",
    "we've": "we have",
    "what's": "what is",
    "whats": "what is",
    "where's": "where is",
    "wo/": "with out",
    "won't": "will not",
    "wouldn't": "would not",
    "wo": "with out",
    "w": "with",
    "you'd": "you would",
    "you'll": "you will",
    "you're": "you are",
    "you've": "you have",
    "upd8": "update"
}

